"""Create the fixed glyph-run fixture used by native raster validation.

The fixture records HarfBuzz shaping results in font units. Windows consumes
these runs through DirectWrite without invoking a Windows shaping engine, so
the resulting evidence is raster proof only. Linux FreeType consumes the same
runs as an independent raster reference.
"""

from __future__ import annotations

import hashlib
from pathlib import Path

import uharfbuzz as hb
from fontTools.ttLib import TTFont


ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "tools" / "native-raster-runs.tsv"
FONTS = (
    ("full-regular", "release/v1.003/Buoy-Regular.ttf", "Regular"),
    ("latin-regular", "release/v1.003/Buoy-Regular-Latin.ttf", "Regular"),
    ("full-medium", "release/v1.003/Buoy-Medium.ttf", "Medium"),
    ("latin-medium", "release/v1.003/Buoy-Medium-Latin.ttf", "Medium"),
)
SIZES = (11, 12, 13, 14, 16, 18)
TEXTS = (
    ("stems", "HIT inl IIl1 1408"),
    ("round-punctuation", "“Buoy,” ‘round’ (soft);"),
    ("digits", "0123456789 $1,250,000.00 -12,004.10"),
    ("accents", "café cafe\u0301 Ő O\u030b Ω Ω q\u0301 q\u0301\u0308 i\u0357"),
)


def csv(values: list[int]) -> str:
    return ",".join(str(value) for value in values)


def main() -> None:
    rows = [
        "# Generated by tools/make_native_raster_runs.py.",
        "# HarfBuzz shapes these strings locally. Native jobs only rasterize the fixed glyph runs.",
        "font_id\tfont_path\tsha256\tweight\tupem\tsize_px\tcase_id\ttext\tglyph_ids\tx_advances\ty_advances\tx_offsets\ty_offsets",
    ]
    for font_id, relative_path, weight in FONTS:
        path = ROOT / relative_path
        data = path.read_bytes()
        digest = hashlib.sha256(data).hexdigest()
        upem = TTFont(path)["head"].unitsPerEm
        face = hb.Face(data)
        font = hb.Font(face)
        font.scale = (upem, upem)
        hb.ot_font_set_funcs(font)
        for size in SIZES:
            for case_id, text in TEXTS:
                buffer = hb.Buffer()
                buffer.add_str(text)
                buffer.direction = "ltr"
                buffer.script = "Latn"
                buffer.language = "en"
                hb.shape(font, buffer, {"kern": True, "tnum": True})
                glyph_ids = [info.codepoint for info in buffer.glyph_infos]
                positions = buffer.glyph_positions
                if not glyph_ids or 0 in glyph_ids:
                    raise SystemExit(f"{font_id} {case_id} maps to an empty or .notdef glyph")
                if case_id == "digits" and len({position.x_advance for position in positions[:10]}) != 1:
                    raise SystemExit(f"{font_id} did not shape tabular digits")
                fields = (
                    font_id,
                    relative_path,
                    digest,
                    weight,
                    str(upem),
                    str(size),
                    case_id,
                    text,
                    csv(glyph_ids),
                    csv([position.x_advance for position in positions]),
                    csv([position.y_advance for position in positions]),
                    csv([position.x_offset for position in positions]),
                    csv([position.y_offset for position in positions]),
                )
                if any("\t" in field or "\n" in field for field in fields):
                    raise SystemExit("TSV field contains a tab or newline")
                rows.append("\t".join(fields))
    OUT.write_text("\n".join(rows) + "\n", encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)} ({len(rows) - 3} runs)")


if __name__ == "__main__":
    main()
